version: '2'

volumes:
  nodered-data:

services:
  node_red:
    build: ./nodered
    restart: always
    privileged: true
    ports:
      - "1880:1880"
    volumes:
      - "nodered-data:/data"
    environment:
      - NODE_RED_USER=${NODE_RED_USER}
      - NODE_RED_PASSWORD=${NODE_RED_PASSWORD}
      - NODE_RED_PLAIN_PASSWORD=${NODE_RED_PLAIN_PASSWORD}